# Generated by Django 5.1 on 2024-10-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_item', to='warehouse.warehouse'),
        ),
    ]
