# Generated by Django 5.1 on 2024-10-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_bookreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
