# Generated by Django 5.1 on 2024-10-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0007_remove_book_price_remove_book_stock'),
        ('warehouse', '0002_warehouse_count_alter_warehouse_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.book')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='warehouse.warehouse')),
                ('from_warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out_item', to='warehouse.warehouseitem')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouse.warehouse')),
                ('to_warehouse_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in_item', to='warehouse.warehouseitem')),
            ],
        ),
    ]
