# Generated by Django 5.1 on 2024-10-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
        ('warehouse', '0002_warehouse_count_alter_warehouse_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouseitem'),
        ),
    ]
